language: erlang

os: linux
otp_release:
  - 20.0
  - 19.3
  - 18.3

script: rebar3 eunit
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
  - sudo pip install codecov
script:
  - ./rebar3 compile
  - ./rebar3 xref
  - ./rebar3 eunit
  - ./rebar3 dialyzer
  - ./rebar3 edoc
  - ./rebar3 cover
  - ./rebar3 covertool generate
  - cp _build/test/covertool/splay_tree.covertool.xml ./cobertura.xml

after_success:
  - codecov
